/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BOARD_UI_INSTALL_PATH "/usr/local/share/le/tools/board"

#define BOARD_UI_SOURCE_PATH "/Users/svetlana/Developer/le/tools/board/ui"

